### ISSUE TITLE
Cannot create note because it is a duplicate

### ISSUE THREAD

**Issue by Luiz-nyan** [ShootingKing-AM/Obsidian_to_Anki#116]
The plugin doesnt allow to create new cards when the first field isnt "Front", if we change the order of the fields and put other like "Obsidian Link", the plugin stop creating cards showing in the console that "file noteName.md due to error cannot create note because it is a duplicate"
![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/40703441/f4a7fe6c-9ba0-4ebf-a2e7-f49418e511af)

**Comment by ShootingKing-AM** [comment]
Why do you not specify the first field as Front then ?
