### ISSUE TITLE
Add option to set a directory to scan instead of the whole vault

### ISSUE THREAD

**Issue by serpro69** [ShootingKing-AM/Obsidian_to_Anki#153]
Hi,

First of all thanks a lot for maintaining this plugin!

I have long struggled with the fact that that the plugin always scans the entire vault and there is no option in the settings to override this behavior, which I would think should be quite simple to implement.

Let me give you an example of why I think this could be useful.
I have quite big a vault with >40k markdown files. My anki cards' notes, however, are separated in their own directory and are much smaller in size. Scanning the entire vault is therefore a huge overkill. My current workaround is to delete almost everything from the vault, do a scan, and then restore deleted files...
It would be nice if I could instead set a specific directory for the plugin to scan via settings, and ignore the rest of the vault.

**Comment by serpro69** [comment]
I don't see a ready function in obsidian api to get all files from a specific folder, instead of all files from the vault, but maybe something like this would do the trick?

```
/**
 * Recursively traverse a TFolder and return all TFiles.
 * @param tfolder - The TFolder to start the traversal from.
 * @returns An array of TFiles found within the folder and its subfolders.
 */
getAllTFilesInFolder(tfolder) {
  const allTFiles = [];

  // Check if the provided object is a TFolder
  if (!(folder instanceof TFolder)) {
    return allTFiles;
  }

  // Iterate through the contents of the folder
  folder.children.forEach((child) => {
    if (child instanceof TFile) {
      // If it's a TFile, add it to the result
      allTFiles.push(child);
    } else if (child instanceof TFolder) {
      // If it's a TFolder, recursively call the function on it
      const filesInSubfolder = getAllTFilesInFolder(child);
      allTFiles.push(...filesInSubfolder);
    }
    // Ignore other types of files or objects
  });

  return allTFiles;
}

```

**Comment by serpro69** [comment]
I've tested the following change by directly updating the main.js in the vault, and it seems to work just fine

```diff
diff --git a/.obsidian/plugins/obsidian-to-anki-plugin/main.js b/.obsidian/plugins/obsidian-to-anki-plugin/main.js
index b0e4d500..ef6d7d7e 100644
--- a/.obsidian/plugins/obsidian-to-anki-plugin/main.js
+++ b/.obsidian/plugins/obsidian-to-anki-plugin/main.js
@@ -53372,6 +53372,21 @@ class MyPlugin extends obsidian.Plugin {
             }
         }
     }
+    getAllTFilesInFolder(tfolder) {
+      const allTFiles = [];
+      if (!(tfolder instanceof obsidian.TFolder)) {
+        return allTFiles;
+      }
+      tfolder.children.forEach((child) => {
+        if (child instanceof obsidian.TFile) {
+          allTFiles.push(child);
+        } else if (child instanceof obsidian.TFolder) {
+          const filesInSubfolder = getAllTFilesInFolder(child);
+          allTFiles.push(...filesInSubfolder);
+        }
+      });
+      return allTFiles;
+    }
     async scanVault() {
         new obsidian.Notice('Scanning vault, check console for details...');
         console.info("Checking connection to Anki...");
@@ -53384,7 +53399,16 @@ class MyPlugin extends obsidian.Plugin {
         }
         new obsidian.Notice("Successfully connected to Anki! This could take a few minutes - please don't close Anki until the plugin is finished");
         const data = await settingToData(this.app, this.settings, this.fields_dict);
-        const manager = new FileManager(this.app, data, this.app.vault.getMarkdownFiles(), this.file_hashes, this.added_media);
+        
+        let markdownFiles = [];
+        const ankiScanDir = this.app.vault.getAbstractFileByPath("10_anki/test");
+        if (ankiScanDir instanceof obsidian.TFolder) {
+          console.info("Found dir")
+          markdownFiles = this.getAllTFilesInFolder(ankiScanDir);
+        } else {
+          new Notice("Error: incorrect path")
+        }
+        const manager = new FileManager(this.app, data, markdownFiles, this.file_hashes, this.added_media) 
         await manager.initialiseFiles();
         await manager.requests_1();
         this.added_media = Array.from(manager.added_media_set);
```

**Comment by ShootingKing-AM** [comment]
Hello, you can get some hints from https://github.com/ShootingKing-AM/Obsidian_to_Anki/blob/master/.github/workflows/build.yml file on how to develop locally.

**Comment by serpro69** [comment]
Thanks! Was going to look at the workflows as well :)
But do you find this useful and/or willing to add this functionality to the plugin? I can try to whip up a PR if you like, though might take some time to do it right. I'd want to add tests as well if I do some changes, and I haven't looked at the test part of the code yet.

**Comment by ShootingKing-AM** [comment]
Yeah sure, looks like good feature, i also vaguely remeber it being requested elsewhere. PRs are always welcome :3 Tests are also required so that we can deploy new features faster, you can ask me if you have any questions :)

**Comment by serpro69** [comment]
I've made a draft PR here #154 
But not entirely sure how to add good tests for this change.
