### ISSUE TITLE
Some Flashcards are not added, even though I don't have any errors in Obsidian Console

### ISSUE THREAD

**Issue by Cloufish** [ShootingKing-AM/Obsidian_to_Anki#201]
Flashcards are not added, even though I don't have any errors in Obsidian Console
**Just to be clear, I didn't installed your version/fork of the plugin** - Is it possible to do that from Obsidian GUI?

I use a specific regex expression:
`((?:[^\n][\n]?)+) #flashcard ?\n*((?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))+)`
That is defined in the original documentation

However, when I run the plugin some Flashcards are created, and some not

1. I checked regex expression and two of them (all tested) match the expression 
2. I use Basic Flashcard Type, and the Fields are being detected
3. I have around 400 flashcards in my file, but only 290 are being created
4. I cleared every setting from the menu—but this didn't help.
5. I've set `allowDuplicate: true` in `main.js` in `.obsidian/plugins/obsidian-to-anki-plugin` folder
6. Each flashcard has at least 2 new line characters

![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/32965886/178c0aff-36ae-4ec4-99b3-e980044f7684)
![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/32965886/cb9faf8c-305f-4d0a-bedf-acbef692b258)

**Comment by ShootingKing-AM** [comment]
Share the Obsidian file also, whos cards are not added. Also the file for which the cards are added.

Share your anki showing the cards which are added and show that some cards are not added.

**Comment by Cloufish** [comment]
Unfortunately I can't give you a whole file
It contains confidential information
It's also in Polish

But I can give you the selected ones.

**The ones not added:**
```
Czy można zamieniać drukarki fiskalne? #flashcard 
- Nie


Co gdy drukarka wciąga/zacina papier #flashcard 
1. Poproszenie o zdjęcie rolki papieru, drukarki
2. OnSite 

```
**The ones added:**

```
Jak zmienić SLA? #flashcard 
- W zgłoszeniu Różne -> Pola dodatkowe
<!--ID: 1704043474821-->


Co jeśli monitor jest "Not Logged"? #flashcard 
- Należy ustawić auto-logowanie na MultiPoint Managerze
<!--ID: 1704043474392-->

```
![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/32965886/a96a8024-ab08-4e5c-92c2-c2665ba1cdf0)

![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/32965886/cad728a2-7270-46a0-a03f-216318d4252e)

**Comment by ShootingKing-AM** [comment]
Can you check regex for both ones, if its matching ? from regex101 site. With the original file ?

![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/4137788/b5663985-c14d-48e8-8ca8-e74b45bd2b78)

**Comment by Cloufish** [comment]
I've checked the **whole file**

Many of my cards didn't have `#flashcard` hashtag. Around 10
I fixed them and they appeared.

But there are plenty of other cards that were not added
Each of them matches the Regex expression from the website

**Comment by Cloufish** [comment]
I've checked **the whole** file

1. 10 of Flashcards didn't have the `#flashcard`  - I added it

But other than that, they're plenty of not added Flashcards, that are detected by the regex101

**Comment by ShootingKing-AM** [comment]
On my side its, working.
![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/4137788/a59888d4-6b4b-464e-823f-e56b25aa5444)
![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/4137788/093881f1-4cf5-4fe4-bc4f-da7ba1e2d67c)

You can try making a small obsidian file and paste those which are not being added for test. or send me the whole file so that i can try to reproduce on my end.

**Comment by Cloufish** [comment]
Yeah,

Doing it and diving this huge file into 8 smaller ones fixes the issue

But this solution doesn't satisfy me :/
I thought that I could manage one file to create Anki Flashcards. 
And now I have 8 of the files I need to manage, fix

**Comment by ShootingKing-AM** [comment]
Thats not a solution, but to solve it properly you need to provide more information.

Atleast not the content, how big is the file ? Its size and content length ?

**Comment by Cloufish** [comment]
It has 12506 words
85477 characters
8,8Kb

**Comment by basti-who** [comment]
Hi, I have the same issues with my regex. I'm using a dedicated callout since a few years:

> [!Anki] What are the ten Azure Cloud Shell Features?
> - Is temporary and requires a new or existing Azure Files share to be mounted.
> - Offers an integrated graphical text editor based on the open-source Monaco Editor.
> - Authenticates automatically for instant access to your resources.
> - Runs on a temporary host provided on a per-session, per-user basis.
> - Times out after 20 minutes without interactive activity.
> - Requires a resource group, storage account, and Azure File share.
> - Uses the same Azure file share for both Bash and PowerShell.
> - Is assigned to one machine per user account.
> - Persists $HOME using a 5-GB image held in your file share.
> - Permissions are set as a regular Linux user in Bash.



> [!Anki] What do you need for Azure Cloud Shell?
> Azure subscription for Azure file share with monthly costs
> ![[20240104092224.png]]


> [!Anki] How to install all Azure Powershell Modules for current user?
> ```powershell
> Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
> ```


> [!Anki] How to update Azure Powershell Modules?
> ```powershell
> Update-Module -Name Az -Force
> ```

> [!Anki] How to get properties of created disk `$diskName` in Az Powershell?
> ```powershell
> Get-AzDisk -ResourceGroupName $resName -DiskName $diskName
> ``` 


For some of my cards it works for some not and I do not see a pattern... This is my regex which I use for a few years now (stopped creating cards about a year ago...)

(?:\> \[!Anki\]) ([^\n]+)\n(.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)

**Comment by basti-who** [comment]
I've also splitted my file into smaller peaces and can confirm that this fixed my issues for the small files with not more than 13 cards to add. In my main file where 31 cards needs to be added 19 in the middle are missing. All caches have been cleared before.

**Comment by ShootingKing-AM** [comment]
whats the size of your note ? Character length, Can you upload your whole note file @basti-who

**Comment by basti-who** [comment]
[anki_withIDs.md](https://github.com/ShootingKing-AM/Obsidian_to_Anki/files/13841014/anki_withIDs.md)
[anki_withoutIDs.md](https://github.com/ShootingKing-AM/Obsidian_to_Anki/files/13841015/anki_withoutIDs.md)

Both are really small with around 6KB. I've cleaned up one of them (anki_withoutIDs) so you can use it for debugging. After the clean up I've tried to run it again (to be added on a different deck in Anki) and the result can be seen in anki_withIDs.md. I'm using the Basic Notetype (Back, Front) with the regex: 

`(?:\> \[!Anki\]) ([^\n]+)\n(.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)`
