### ISSUE TITLE
Want to add folders that exclude synchronization

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [ShootingKing-AM/Obsidian_to_Anki#6]
- Want to add folders that exclude synchronization, similar to this branch https://github.com/aviral-batra/Obsidian_to_Anki

- I think this may be very necessary or even necessary, because obsidian has some files that do not want to synchronize, and the regular expression I set is title style (four-level title printing), so I hope to improve it

- Or you can make a branch in the aviral version to continue to improve, the original Pseudonium/Obsidian_to_Anki has too many problems at present

**Comment by ShootingKing-AM** [comment]
this is similar to #153
