### ISSUE TITLE
Rendering embedded notes

### ISSUE THREAD

**Issue by Luiz-nyan** [ShootingKing-AM/Obsidian_to_Anki#99]
I would like to request a feature to render embedded notes in the format "![[noteName]]" within the fields of "front" or "back" or "extra"
What's the use of that?
Well, it would be interesting because in this case, you can make references to your notes already created instead of creating a new text for the back of the card. If you already have a note ready and just want to reference what was done in the flashcard, just link it with a ![[noteName^paragraph]] which will be much more practical to have a context about what the inserted note is about. It can also serve as a summary to avoid losing the context of the flashcards.
![image](https://github.com/ShootingKing-AM/Obsidian_to_Anki/assets/40703441/390b081b-0a07-494a-8ede-cce39983d50e)

**Comment by ShootingKing-AM** [comment]
This is similar to https://github.com/Pseudonium/Obsidian_to_Anki/issues/347

**Comment by ShootingKing-AM** [comment]
Need further investigation (seems there was a solution provided there), was just linking both issues, so one can follow both for updates.

**Comment by GottZ** [comment]
@ShootingKing-AM I found a permanent fix by swapping rendering api's due to deprecation.

might be relevant here: https://github.com/blacksmithgu/obsidian-dataview/pull/2266
